// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// 声明形参
RWStructuredBuffer<float3> _ParticlePositions;

float _DeltaTime;
float _Speed;
float _Time;

// 划分线程组
[numthreads(64,1,1)]

// 6.执行计算
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // 读取当前位置
    float3 pos = _ParticlePositions[id.x];
    
    // 修改Y轴做正弦运动
    pos.y += sin(_Time * _Speed + pos.x) * _DeltaTime;
    
    // 写回
    _ParticlePositions[id.x] = pos;
}
