// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// 声明形参
RWStructuredBuffer<float3> _ParticlePositions;
RWStructuredBuffer<float3> _OutputData;    // 输出缓冲区
float _DeltaTime;
float _Speed;

// 划分线程组
[numthreads(256,1,1)]

// 6.执行计算
void CSMain (uint3 id : SV_DispatchThreadID)
{
    _OutputData[id.x] = _ParticlePositions[id.x].y + sin(_DeltaTime * _Speed + _ParticlePositions[id.x].x) * _DeltaTime;
}
